using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BombingArea : MonoBehaviour
{
    //è¿™æ˜¯è½°ç‚¸åŒºçš„è„šæœ¬ï¼Œæ§åˆ¶è½°ç‚¸åŒºç›¸å…³çš„æ‰€æœ‰é€»è¾‘ğŸ’£
    // Start is called before the first frame update
    private bool bombing = false;//æ˜¯å¦æ­£åœ¨è½°ç‚¸
    public GameObject shell;//ç‚®å¼¹æ¸¸æˆç‰©ä½“
    // [Tooltip("ç‚®å¼¹é˜´å½±Yè½´çš„åç§»é‡")]
    // public float shellShadowYOffset;//ç‚®å¼¹é˜´å½±Yè½´çš„åç§»é‡ï¼Œå› ä¸ºå¤æ‚åŸå› ï¼Œå¿…é¡»ä½¿ç”¨æ­¤å˜é‡è°ƒæ•´é˜´å½±çš„Yä½ç½®

    private float minimumTimeInterval;
    private float maximumTimeInterval;//ç”Ÿæˆç‚®å¼¹çš„æœ€å°å’Œæœ€å¤§æ—¶é—´é—´éš”

    private float maxOffSetOfShell;//ç”Ÿæˆç‚®å¼¹ç¦»ç©å®¶çš„æœ€å¤§åç§»é‡
    private float leftTime = 0f;
    private IndexRecoder indexRecoder;
    private M_Player player;
    private float shellHeight;

    void Start()
    {
        Init();
    }

    // Update is called once per frame
    void Update()
    {
        if(bombing) Bomb();
    }

    private void Init()
    {
        indexRecoder = FindObjectOfType<IndexRecoder>();
        minimumTimeInterval = indexRecoder.bombingAreaMinimumTimeInterval;
        maximumTimeInterval = indexRecoder.bombingAreaMaximumTimeInterval;
        maxOffSetOfShell = indexRecoder.bombingAreaMaxOffSetOfShell;
        shellHeight = indexRecoder.bombingAreaShellHeight;
        player = FindObjectOfType<M_Player>();
    }


    private void Bomb()
    {
        if(leftTime <= 0f)
        {
            Instantiate(shell,//ç”Ÿæˆç‚®å¼¹
                        player.transform.position +  //ä»¥ç©å®¶ä½ç½®
                        new Vector3(Random.Range(-maxOffSetOfShell,maxOffSetOfShell),//åŠ ä¸Šæ°´å¹³æ–¹å‘çš„åç§»é‡
                                                shellHeight,0),//ç«–ç›´æ–¹å‘ç»™é«˜åº¦
                        Quaternion.identity);
            leftTime = Random.Range(minimumTimeInterval,maximumTimeInterval);
        }
        else leftTime -= Time.deltaTime;
    }

    void OnTriggerEnter2D(Collider2D other)
    {
        if(other.tag == "Player")//å½“ç©å®¶è¿›å…¥è½°ç‚¸åŒº
        {
            bombing = true;
        }
    }

    void  OnTriggerExit2D(Collider2D other)
    {
        if(other.tag == "Player")//å½“ç©å®¶é€€å‡ºè½°ç‚¸åŒº
        {
            bombing = false;
        }
    }
}
