using System.Collections;
using System.Collections.Generic;
using System.Security.Cryptography;
using UnityEngine;

public class BoomShader : MonoBehaviour
{
    //è¿™æ˜¯æ§åˆ¶ç‚¸å¼¹çˆ†ç‚¸åå†²å‡»æ³¢äº§ç”Ÿçš„è„šæœ¬ï¼Œæ˜¯éœ„é…±å†™çš„ğŸ¤”
    public Material boomMaterial;//çˆ†ç‚¸shaderçš„æè´¨
    private Vector2 boomPos;//çˆ†ç‚¸åæ ‡
    private bool isBoom = false;//æ˜¯å¦çˆ†ç‚¸
    // Start is called before the first frame update
    void Start()
    {
        boomMaterial.SetFloat("WaveSpread_Value",0);
        isBoom = true;
        Invoke("setBoom",0.5f);
    }

    // Update is called once per frame
    void Update()
    {
        if (isBoom)
        {
            UpdateBoom();
        }
    }
    
    private void UpdateBoom()
    {
        boomPos = Camera.main.WorldToViewportPoint(new Vector2(transform.position.x, transform.position.y));
        boomMaterial.SetVector("Center",boomPos);
        boomMaterial.SetFloat("WaveSpread_Value",boomMaterial.GetFloat("WaveSpread_Value")+0.2f);
    }

    private void setBoom()
    {
        isBoom = false;
        boomMaterial.SetFloat("WaveSpread_Value",0);
        Destroy(gameObject);
    }

    public void SetboomPos(Vector2 pos)
    {
        this.boomPos = pos;
    }
}
