using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Interactions;
using UnityEngine.UI;
using Cinemachine;

public class M_Player : MonoBehaviour
{
    //ç©å®¶ç±»ï¼Œä¸»è¦ç”¨æ¥æ§åˆ¶ç©å®¶
    private IndexRecoder indexRecoder;//è®°å½•ç»„ä»¶ï¼Œå†…å­˜æ–¹ä¾¿ä¿®æ”¹çš„å‚æ•°
    private Vector2 velocity;//é€»è¾‘é€Ÿåº¦ï¼Œé€šè¿‡è®¡ç®—è·å¾—ï¼Œæœ€ååŠ åœ¨ç†è®ºé€Ÿåº¦ä¸Š
    private Rigidbody2D m_rigidbody;//è‡ªèº«åˆšä½“ç»„ä»¶
    private int inputDir;//è¾“å…¥æ–¹å‘æ–¹å‘,-1\0\1
    private int faceDir;//é¢éƒ¨æœå‘ï¼Œ-1ã€1
    private float runSpeedMultiple = 1f;//é€Ÿåº¦å€ç‡ï¼Œåœ¨æŒ‰ä¸‹å’Œé‡Šæ”¾è·‘æ­¥åè¢«ä¿®æ”¹
    [Tooltip("æ‰€æ•æ‰åˆ°çš„å¯äº¤äº’å¯¹è±¡,ä¸è¦æ‰‹åŠ¨èµ‹å€¼ï¼Œè¿™ä¸ªä¼šè‡ªå·±æ•æ‰")]
    public Interactive catched;//æ‰€æ•æ‰åˆ°çš„å¯äº¤äº’å¯¹è±¡
    private bool throwingState = false;//è®°å½•å½“å‰æ˜¯å¦åœ¨æŠ•æ·çŠ¶æ€
    private PlayerInput playerInput;//è‡ªèº«è¾“å…¥ç»„ä»¶ï¼Œç”¨æ¥åˆ‡æ¢æ“æ§åœ°å›¾
    private bool canAdjustTheAngle = false;//è®°å½•æ­¤æ—¶è‡ªå·±æ˜¯å¦èƒ½è°ƒæ•´æŠ•æ·è§’
    [SerializeField]
    private float throwingAngle = 45f;//è®°å½•æŠ•æ·çš„è§’åº¦.é»˜è®¤æ˜¯45Â°
    private float throwingAngleDir;//è®°å½•æ­¤æ—¶æŠ•æ·è§’åº¦å˜åŒ–çš„é€Ÿåº¦ï¼ŒåŒ…æ‹¬å¤§å°å’Œæ–¹å‘ï¼Œ-1~1è¡¨ç¤º
    [Tooltip("æŠ•æ·ç‰©çš„é¢„åˆ¶ä½“")]
    public GameObject missile;//æŠ•æ·ç‰©çš„é¢„åˆ¶ä½“
    [Tooltip("æŠ•æ·ç‰©æŠ›å‡ºç‚¹")]
    public Transform throwOffset;//è®°å½•ä¸€ä¸‹æŠ›å‡ºç‚¹çš„ä½ç½®
    private Animator M_Animator;
    private float strengthOfThrowing;//æŠ•æ·åŠ›åº¦ï¼Œæ¯æ¬¡å’ŒæŠ•æ·ç‰©å †äº¤äº’ï¼Œéƒ½ä¼šæ›´æ–°è¿™ä¸ªæ•°å€¼
    public AudioSource machineAudio;
    private bool isCovered = false;//è®°å½•è‡ªèº«ç°åœ¨æ˜¯å¦è¢«æ©æŠ¤ï¼ŒæŒ¡æ¿ä¸­ä½¿ç”¨
    void Start()
    {
        indexRecoder = FindObjectOfType<IndexRecoder>();//è·å–æ•°å€¼è®°å½•ç»„ä»¶ï¼Œæ–¹ä¾¿ç­–åˆ’ä¿®æ”¹æš´éœ²å‚æ•°    
        m_rigidbody = GetComponent<Rigidbody2D>();//è·å–è‡ªèº«åˆšä½“ç»„ä»¶
        faceDir = 1;//é»˜è®¤é¢éƒ¨æœå³
        playerInput = GetComponent<PlayerInput>(); //è·å–è‡ªèº«è¾“å…¥ç»„ä»¶
        M_Animator = GetComponent<Animator>();

        //ä¸ºäº†è§£å†³warmingï¼Œæœ€åé˜¶æ®µè¯·åˆ é™¤ï¼Œåˆ°é‚£æ—¶åº”è¯¥ä¸ä¼šå†æœ‰è­¦å‘Š
        if(inputDir == 0){}
        //
    }

    // Update is called once per frame
    void Update()
    {
        AdjustTheAngle();
    }

    void FixedUpdate(){}

    // void OnAnimatorMove()//Unityçš„å›è°ƒå‡½æ•°ï¼Œè¿™æ ·åšèƒ½è§£å†³æ¨¡å‹æ— æ³•è½¬å‘çš„é—®é¢˜ï¼Œæ¯å¸§è°ƒç”¨ä¸€æ¬¡
    // {
    //     //Debug.Log(playerAnimator.deltaPosition.magnitude);
    //     m_rigidbody.MovePosition(m_rigidbody.position + (Vector2)(M_Animator.deltaPosition));
    //     //m_RigidBody.MoveRotation(m_Rotation);//å½“ç‰©ä½“æœ‰ç‰©ç†ç»„ä»¶rigidbodyçš„æ—¶å€™ï¼Œå†ä¿®æ”¹ä½ç½®å’Œæ—‹è½¬ä¿¡æ¯å°±ä¸è¦ç”¨transfromäº†ï¼Œç”¨åˆšä½“è‡ªå¸¦çš„Moveç­‰æ–¹æ³•
    // }

    //è¿”å›é¢éƒ¨æœå‘çš„å‡½æ•°ï¼Œåœ¨ä¸Šä¸‹å‘ç‚¹è°ƒç”¨ï¼Œç”¨æ¥åˆ¤æ–­æ˜¯å¦æ‰§è¡Œä¸Šä¸‹å‘åŠ¨ç”»
    public int ReturnFaceDir(){return faceDir;}

    //æ’­æ”¾ä¸Šå‘åŠ¨ç”»
    public void PlayUpAnimation(){M_Animator.SetBool("IsUp",true);}

    //æ’­æ”¾ä¸‹å‘åŠ¨ç”»çš„å‡½æ•°ï¼Œåœ¨ä¸‹å‘ç‚¹è°ƒç”¨
    public void PlayDownAnimation(){M_Animator.SetBool("IsDown",true);}

    //å…³é—­ä¸‹å‘æ¡ä»¶ï¼Œåœ¨åŠ¨ç”»ä¸­æ·»åŠ Eventæ¥æ‰§è¡Œï¼Œé¿å…ä¸‹å‘åŠ¨ç”»é‡å¤æ‰§è¡Œ
    public void StopIsDown(){M_Animator.SetBool("IsDown",false);}

    //ç»™è‡ªç”Ÿåˆšä½“ä¸€ä¸ªå‘ä¸Šçš„é€Ÿåº¦ï¼Œä¸ç„¶æ— æ³•è§£å†³åŠ¨ç”»ä¸Šå‘yè½´è¢«é‡åŠ›æ§åˆ¶çš„é—®é¢˜
    public void GiveAUpForce(){
        if(gameObject.name == "ä»–çˆ¸")
        m_rigidbody.velocity = new Vector2(0,6);
        else
        m_rigidbody.velocity = new Vector2(0,8);//åŒ¹é…ä¸åŒçš„ä¸¤ä¸ªå‘
    }


    //å…³é—­ä¸Šå‘æ¡ä»¶ï¼Œé¿å…é‡å¤è§¦å‘
    public void StopIsUp(){M_Animator.SetBool("IsUp",false);}

    //è°ƒæ•´æŠ•æ·è§’åº¦çš„å‡½æ•°
    private void AdjustTheAngle()
    {
        if(canAdjustTheAngle)//å¦‚æœç©å®¶èƒ½è°ƒæ•´è§’åº¦
        {
            throwingAngle += throwingAngleDir//åˆ™è®©ç°åœ¨çš„æŠ›å‡ºè§’åº¦åŠ ä¸Šå˜åŒ–çš„é€Ÿåº¦
                             * indexRecoder.rateOfChangeOfThrowingAngle//ä¹˜ä»¥å˜åŒ–çš„é€Ÿç‡
                             * Time.deltaTime;//ä½¿å…¶ä¸æ—¶é—´æ— å…³
            Debug.DrawLine(throwOffset.position,
                            new Vector3(transform.position.x + 100*Mathf.Cos(throwingAngle),
                                        transform.position.y + 100*Mathf.Sin(throwingAngle),
                                        transform.position.z),
                            Color.red);
           DrawPath(); 
        }
    }

    public void ChangeInputMapToNull()
    {
        playerInput.SwitchCurrentActionMap("NullMap");
    }

    public void ChangeInputMapToNormal()
    {
        playerInput.SwitchCurrentActionMap("PlayerNormal");
    }

    //å½“ç©å®¶åœ¨ä¿®ç”µæŠ¥æœºåœ°å›¾ä¸‹æŒ‰ä¸‹äº¤äº’é”®è§¦å‘
    public void OnComfirm(InputAction.CallbackContext context)
    {
        if(context.started) catched.Comfirm();
    }

    //å½“æ°´å¹³è½´æœ‰è¾“å…¥
    public void OnMoveHorizons(InputAction.CallbackContext context)
    {
        float value = context.ReadValue<float>();
        M_Animator.SetBool("IsWalking",true);
        //è¾“å…¥åªæœ‰å¯¹ç§»åŠ¨æ–¹å‘å’Œé¢éƒ¨æœå‘çš„æ›´æ”¹
        if(value > 0)
        {
            inputDir = 1;
            faceDir = 1;
        }
        
        else if(value < 0) 
        {
            inputDir = -1;
            faceDir = -1;
        }
        else {inputDir = 0;
              M_Animator.SetBool("IsWalking",false);}
        //ä¿®æ”¹é¢éƒ¨æœå‘
        transform.localScale = new Vector3(
            Mathf.Abs(transform.localScale.x)*faceDir,
            transform.localScale.y,
            transform.localScale.z);
        if(faceDir == -1)throwingAngle = 46f;
        else throwingAngle = 45f;
    }

    //ç›‘å¬æŠ•æ·æŒ‰é”®çš„å‡½æ•°
    public void OnThrow(InputAction.CallbackContext context)
    {
        if(context.started)//å¦‚æœæŒ‰ä¸‹æŠ•æ·é”®ï¼Œè¡¨ç¤ºå¯ä»¥å¼€å§‹æ§åˆ¶è§’åº¦äº†
        {
            canAdjustTheAngle = true;
            //åŠ¨ç”»ï¼šè¿›å…¥å‡†å¤‡ä¸¢çš„åŠ¨ç”»
            M_Animator.SetBool("ReadyToThrow", true);
        }
        if(context.canceled)//å¦‚æœæ˜¯åˆšæ¾å¼€æŠ•æ·é”®ï¼Œè¡¨ç¤ºè¦ä¸¢ä¸œè¥¿äº†
        {
            if(throwingState)
            {
                M_Animator.SetBool("NowThrow",true);//åŠ¨ç”»ï¼šæ‰§è¡Œä¸¢è¿™ä¸ªåŠ¨ä½œ
                Throw();//å¦‚æœå¤„äºæŠ•æ·é˜¶æ®µï¼Œåˆ™è§¦å‘ä¸¢
            }
        }
    }

    public void OnQuit(InputAction.CallbackContext context)
    {
        if(context.started) catched.Quit();//å¦‚æœæŒ‰ä¸‹é€€å‡ºæŒ‰é’®ï¼Œåˆ™æ‰§è¡Œæ•æ‰åˆ°ç‰©ä½“çš„é€€å‡ºåŠŸèƒ½
    }

    //å¦‚æœæ­£å¤„äºæŠ•æ·çŠ¶æ€ï¼Œåˆ™é€€å‡ºæŠ•æ·çŠ¶æ€çš„ç›‘å¬å‡½æ•°
    public void OnThrowQuit(InputAction.CallbackContext context){if(throwingState)StartCoroutine("QuitThrowingsState");}

    //ç›‘å¬ä¿®æ”¹æŠ•æ·è§’åº¦çš„å‡½æ•°
    public void OnAdjustTheAngle(InputAction.CallbackContext context)
    {throwingAngleDir = context.ReadValue<float>();}//æŠŠæ”¶åˆ°çš„è½´çš„å€¼äº¤ç»™è§’åº¦å˜åŒ–çš„å¤§å°å’Œæ–¹å‘

    //æ§åˆ¶æŠ•æ·ç›¸å…³çš„å…·ä½“å‡½æ•°
    private void Throw()
    {
        Rigidbody2D rigidbodyOfMissile = //å¹¶ä¸”è·å¾—è¿™ä¸ªæŠ•æ·ç‰©èº«ä¸Šçš„åˆšä½“ç»„ä»¶
            Instantiate(missile,throwOffset.position,Quaternion.identity).GetComponent<Rigidbody2D>();//ç”Ÿæˆä¸€ä¸ªæŠ•æ·ç‰©
        
        //ç»™è¿™ä¸ªæŠ•æ·ç‰©èµ‹äºˆé€Ÿåº¦ï¼Œç”±ç›®å‰çš„è§’åº¦å†³å®š
        rigidbodyOfMissile.velocity = new Vector2(strengthOfThrowing*Mathf.Cos(throwingAngle),
                                                  strengthOfThrowing*Mathf.Sin(throwingAngle));
        
        //æ‰”å®Œåé€€å‡ºæŠ•æ·çŠ¶æ€å¹¶ä¸”é‡ç½®ç›¸å…³å‚æ•°
        StartCoroutine("QuitThrowingsState");
    }
    //åœ¨æŠ•æ·ç‰©å †ä¸­è°ƒç”¨ï¼Œæ¯æ¬¡å‘¼å«æŠ•æ·ç‰©å †ï¼Œéƒ½é’ˆå¯¹æ­¤å †æ›´æ–°æŠ•æ·åŠ›åº¦
    public void ChangeStrengthOfThrowingTo(float num)
    {
        strengthOfThrowing = num;
    }

    //è¿›å…¥è·‘æ­¥çŠ¶æ€çš„æ§åˆ¶ä»£ç 
    public void OnRun(InputAction.CallbackContext context)
    {
        if(context.started)//å¦‚æœåˆšæŒ‰ä¸‹è·‘æ­¥é”®
        {
            runSpeedMultiple = indexRecoder.runSpeedMultiple;//æŠŠæœ¬åœ°çš„é€Ÿåº¦å€ç‡å˜æˆæ•°å€¼è®°å½•å™¨ä¸­çš„å€ç‡
            M_Animator.SetBool("IsRunning",true);//æ’­æ”¾è·‘æ­¥åŠ¨ç”»
        }
        else if(context.canceled)//å¦‚æœåˆšæ¾å¼€è·‘æ­¥é”®
        {
            runSpeedMultiple = 1f;//æ¢å¤æœ¬åœ°é€Ÿåº¦å€ç‡ä¸º1
            M_Animator.SetBool("IsRunning",false);//å…³é—­è·‘æ­¥åŠ¨ç”»
        }
    }

    //ç›‘å¬äº¤äº’æŒ‰é”®çš„å‡½æ•°
    public void OnInteraction(InputAction.CallbackContext context)
    {
        if(context.started)
        {
            //å¯äº¤äº’å¯¹è±¡éƒ½æœ‰UIç•Œé¢ã€‚å½“æŒ‰ä¸‹äº¤äº’é”®åï¼Œæ˜¾ç¤ºäº¤äº’ç•Œé¢
            if(catched != null)
            {
                //è§¦å‘äº¤äº’å‡½æ•°ï¼Œåœ¨å…·è±¡ç‰©ä½“ä¸­é‡å†™è¿™ä¸ªè™šæ‹ŸåŠŸèƒ½
                catched.OnCall();
                //å¦‚æœæ•æ‰å¯¹è±¡æ˜¯ç”µè¯çº¿
                if(catched != null && catched.tag == "ç”µè¯çº¿") 
                {
                    //è·å–å…¶ç”µè¯çº¿ç»„ä»¶ï¼Œå¦‚æœå…¶æœªä¿®å¥½ï¼Œåˆ™æ‰§è¡Œä¿®ç†åŠ¨ç”»
                    if(!catched.GetComponent<TelephoneLine>().HasTheBePrepared())
                    M_Animator.SetBool("IsReparing", true);
                }
            }
        }

        if(context.canceled)
        {
            //å¯äº¤äº’å¯¹è±¡ç”µè¯çº¿æ¯”è¾ƒç‰¹æ®Šï¼Œéœ€è¦é¢å¤–æ£€æµ‹æŒ‰é’®æ¾å¼€çš„ç¬é—´
            if(catched != null)
            {
                catched.StopRepareTheTelephoneLine();
                //å¦‚æœæ•æ‰å¯¹è±¡æ˜¯ç”µè¯çº¿ï¼Œåœæ­¢ä¿®ç”µè¯çº¿åŠ¨ç”»
                if(catched.tag == "ç”µè¯çº¿") M_Animator.SetBool("IsReparing", false);
            }
        }
    }

    //å½“ä¿®å¥½äº†ä¸€ä¸ªç”µè¯çº¿ï¼Œå¼ºåˆ¶æ‰“æ–­ä¿®ç”µè¯çº¿åŠ¨ç”»
    public void HasReparedATelephone()
    {
        M_Animator.SetBool("IsReparing", false);
    }


    //ç›‘å¬æ‰“ç”µç çš„å‡½æ•°
    public void OnCoding(InputAction.CallbackContext context)
    {
        if(context.started)
        {
            machineAudio.Play();
            //å¦‚æœåˆšæŒ‰ä¸‹æ‰“ç ï¼ŒæŠŠç”µæŠ¥æœºUIå›¾ç‰‡çš„æŠŠæ‰‹æ›¿æ¢æˆæŒ‰ä¸‹çš„
            catched.ChangeHandleTo(true);
        }

        if(context.canceled)
        {
            machineAudio.Stop();
            //å¦‚æœåˆšæ¾å¼€æ‰“ç ï¼ŒæŠŠç”µæŠ¥æœºUIå›¾ç‰‡çš„æŠŠæ‰‹æ¢æˆæ¾å¼€çš„
            catched.ChangeHandleTo(false);
            //æ ¹æ®æŒ‰ä¸‹æœŸé—´æ—¶é•¿å‘é€æ‰“å‡ºæ¥çš„ç ç»™ç”µæŠ¥æœº
            if(catched != null)
            {
                if(context.duration < indexRecoder.dotRoLineTime)//å¦‚æœå°äºç•Œé™æ—¶é—´
                {
                    catched.Coding(".");
                }
                else
                {
                    catched.Coding("-");
                }
            }
           
        }
    }

    //ä½¿è‡ªèº«è¿›å…¥æŠ•æ·çŠ¶æ€çš„å‡½æ•°
    public void EnterThrowingState()
    {
        throwingState = true;//ä¿®æ”¹è‡ªèº«è®°å½•çŠ¶æ€å˜é‡ï¼Œè¡¨ç¤ºæ­£å¼è¿›å…¥æŠ•æ·çŠ¶æ€
        //1.åˆ‡æ¢æ“æ§åœ°å›¾
        playerInput.SwitchCurrentActionMap("PlayerInThrowing");
        //2.åŠ¨ç”»ç›¸å…³
        M_Animator.SetBool("throwingState",true);//ä½¿è‡ªèº«è¿›å…¥æ¡çŸ³åŠ¨ç”»
    }
    
    //é€€å‡ºæŠ•æ·çŠ¶æ€çš„æ—¶å€™
    public IEnumerator QuitThrowingsState()
    {
        throwingState = false;//æ”¹å˜è‡ªèº«æ ‡è®°
        playerInput.SwitchCurrentActionMap("PlayerNormal");//ä¿®æ”¹è‡ªèº«æ“æ§åœ°å›¾
        if(faceDir == 1) throwingAngle = 45f;//æ¢å¤æŠ•æ·è§’åº¦åˆ°45Â°
        else throwingAngle = 46f;
        canAdjustTheAngle = false;//å¯ä¿®æ”¹è§’åº¦æ ‡è®°æ”¹ä¸ºfalse
        GetComponent<LineRenderer>().enabled = false;//åˆ«ç”»çº¿äº†
        //å…³é—­åŠ¨ç”»æ¡ä»¶
        M_Animator.SetBool("throwingState",false);
        M_Animator.SetBool("ReadyToThrow",false);
        //ä¸ºäº†è§£å†³é—®é¢˜éœ€è¦åˆ°ä¸‹ä¸€å¸§å…³é—­ä¸¢å‡ºåŠ¨ç”»æŒ‡ä»¤
        yield return new WaitForEndOfFrame();
        M_Animator.SetBool("NowThrow",false);
    }

    //æ’­æ”¾ä¸Šä¸‹æ¥¼åŠ¨ç”»çš„å‡½æ•°ï¼Œåœ¨æ¥¼æ¢¯è¾¹çš„è§¦å‘å™¨è°ƒç”¨
    public void PlayDownStairAnimation(){M_Animator.SetBool("IsDownStair",true);}
    public void PlayUpStairAnimation(){}
    //å¤–éƒ¨è°ƒç”¨ï¼Œè®©ç©å®¶è½¬èº«
    public void TurnAround()
    {
        transform.localScale = new Vector3(
            transform.localScale.x*-1,
            transform.localScale.y,
            transform.localScale.z);//è®©ç©å®¶è½¬èº«
    }

    public void YouAreShooting()
    {
        // å½“ç©å®¶è¢«å°„ä¸­æ—¶è°ƒç”¨
        M_Animator.SetBool("IsShootDead",true);
        StartCoroutine("StopShootingAnimation");//æ­¤å¸§ç»“æŸåå…³é—­æ­»äº¡åŠ¨ç”»æ¡ä»¶
    }    
    private IEnumerator StopShootingAnimation()
    {
        yield return new WaitForSeconds(0.1f);
        M_Animator.SetBool("IsShootDead",false);
    }

    public void YouAreCovered(){isCovered = true;}
    public void YouAreLosingCover(){isCovered = false;}
    public bool AreYouCovered(){return isCovered;}

    //ç»˜åˆ¶æŠ•æ·æ›²çº¿çš„å‡½æ•°ï¼Œéå¸¸ğŸ‚
    public void DrawPath()
    {
        //
        LineRenderer line = GetComponent<LineRenderer>();//è·å–ç»„ä»¶
        line.enabled = true;
        int segmentCount = 18;//å®šä¹‰ç‚¹æ•°
        line.positionCount = segmentCount;//ä¼ å…¥ç‚¹æ•°
        float gravity=9.8f;//å®šä¹‰é‡åŠ›å¸¸é‡
        Vector2 fireOffset = new Vector2(throwOffset.position.x - transform.position.x, 
                                         throwOffset.position.y - transform.position.y);
        Vector2[] segments = new Vector2[segmentCount];//å®šä¹‰äºŒç»´å‘é‡æ•°ç»„ï¼Œç”¨æ¥å­˜15ä¸ªç‚¹çš„ä½ç½®
        segments[0].Set(transform.position.x + fireOffset.x, transform.position.y + fireOffset.y);//å®šä¹‰èµ·ç‚¹
        line.SetPosition(0, segments[0]);//æŠŠèµ·ç‚¹ä½ç½®ä¼ å…¥çº¿çš„èµ·ç‚¹    
        for (int i = 1; i < segmentCount; i++)//æ ¹æ®æ—¶é—´ã€å¾ªç¯ç¡®å®šç‚¹çš„ä½ç½®
        {
            float time = i * Time.fixedDeltaTime * 5;//ç±»ä¼¼æ—¶é—´é—´éš”çš„å®šä¹‰ï¼Œä¹Ÿå°±æ˜¯æŠ›ç‰©çº¿ä¸Šçš„xå¤šä¹…å–å€¼ä¸€æ¬¡
            segments[i].x = transform.position.x + //è‡ªèº«ä½ç½®çš„x
                            fireOffset.x + //å‘å°„åç§»é‡çš„x
                            time * strengthOfThrowing * Mathf.Cos(throwingAngle);//æ°´å¹³æ–¹å‘ä½ç§» = v*t
            segments[i].y = (transform.position.y + fireOffset.y + //è‡ªèº«ä½ç½®çš„y
                            time * strengthOfThrowing * Mathf.Sin(throwingAngle) + 
                            (0.5f * gravity * time * time)*-1);//å‚ç›´æ–¹å‘ä½ç§» = vt + 1/2 * g * t^2
            line.SetPosition(i, segments[i]);  //æŠŠç®—å¥½çš„ç‚¹ä¼ å…¥çº¿çš„ç‚¹é›†     
        }
    }

}
