using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Mine : MonoBehaviour
{
    //åœ°é›·ç³»ç»Ÿçš„åœ°é›·ç±»ï¼Œå› ä¸ºç³»ç»Ÿè¿˜ååˆ†ä¸å®Œå–„ï¼Œæ‰€ä»¥æ²¡æœ‰ä»€ä¹ˆå†…å®¹ğŸ¥”
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void OnTriggerEnter2D(Collider2D other)
    {
        //çœ‹çœ‹è¿›æ¥çš„æ˜¯ä¸ªå•¥
        switch(other.tag)
        {
            case "Player"://å¦‚æœæ˜¯ç©å®¶ï¼Œåç»­å¡«å†™æ­»äº¡
                Debug.Log("ç©å®¶è¸©åˆ°åœ°é›·äº†");
                break;
            case "æŠ•æ·ç‰©"://å¦‚æœæ˜¯æŠ•æ·ç‰©ï¼Œé”€æ¯æŠ•æ·ç‰©å’Œè‡ªå·±
                Debug.Log("æŠ•æ·ç‰©ç ¸åˆ°åœ°é›·äº†");
                Destroy(other.gameObject);
                Destroy(gameObject);
                break;
        }
    }
}
