using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Shell : MonoBehaviour
{
    //ç‚®å¼¹ç±»ï¼Œæ§åˆ¶è½°ç‚¸åŒºå†…çš„ç‚®å¼¹å’Œç‚®å¼¹çš„é˜´å½±ğŸ‡
    // Start is called before the first frame update
    public GameObject shadow;//é˜´å½±æ¸¸æˆç‰©ä½“
    private Transform ground;//åœ°é¢çš„ä½ç½®ä¿¡æ¯
    private float shellSpeed;//ç‚®å¼¹é€Ÿåº¦
    private IndexRecoder indexRecoder;
    private float fallingTime;
    private bool isDroping = false;
    private Transform m_shadow;
    public GameObject boomObj;
    public BombingArea M_BombingArea;
    private bool amISpecal = false;//è®°å½•è‡ªå·±æ˜¯ä¸æ˜¯ç‰¹æ®Šçš„çš„å˜é‡ã€‚ç‰¹æ®Šçš„ç‚®å¼¹æ‰èƒ½ç‚¸çƒ‚çŸ³å¤´ã€‚
    private Animator animator;
    private delegate float BuildAFitX(float deleta);
    [Tooltip("è¯·å¡«å…¥é˜´å½±çš„æœ€å¤§å€¼")]
    public float MaxShadowSize;
    [Tooltip("è¯·å¡«å…¥é˜´å½±çš„æœ€å°å€¼")]
    public float MinShadowSize;
    public Animator target;//å¦‚æœæ˜¯ç‰¹æ®Šç‚®å¼¹ï¼Œåˆ™æœ‰targeè¿™ä¸ªå˜é‡ï¼Œå½“è¿™ä¸ªç‚®å¼¹çˆ†ç‚¸ï¼Œè§¦å‘ç›®æ ‡çš„æ­»äº¡åŠ¨ç”»
    
    void Start()
    {
        indexRecoder = FindObjectOfType<IndexRecoder>();
        shellSpeed = indexRecoder.shellSpeed;
        fallingTime = indexRecoder.shellFallingTime;
        ground = GameObject.FindWithTag("åœ°é¢").transform;
        if(!amISpecal)//ç‰¹æ®Šç‚®å¼¹ä¸äºˆé˜´å½±
        {
            m_shadow = Instantiate(shadow,//ç”Ÿæˆä¸€ç‰‡é˜´å½±
                                    new Vector3(transform.position.x,//åœ¨è¿™æšç‚®å¼¹çš„X
                                                ground.transform.position.y + //åœ°é¢çš„Y
                                                M_BombingArea.shellShadowYOffset,//åŠ ä¸Šåç§»é‡
                                                0),
                                    Quaternion.identity)
                                    .transform;
        }
        Invoke("Drop",fallingTime);
        Invoke("DestroySelf",10f);

        animator = GetComponent<Animator>();
    }

    // Update is called once per frame
    void Update()
    {
        if(m_shadow != null) ShadowShock();
        if(isDroping)
        {
            transform.position -= new Vector3(0,shellSpeed*Time.deltaTime,0);
        }

        
    }
    public bool AmISpecal(){return amISpecal;}//å¤–éƒ¨è°ƒç”¨ï¼Œè¿”å›è¿™ä¸ªç‚®å¼¹æ˜¯ä¸æ˜¯ç‰¹æ®Šçš„
    public void YouAreSpecal(){amISpecal = true;}//å¤–éƒ¨è°ƒç”¨ï¼Œç”Ÿæˆç‚®å¼¹æ—¶ï¼Œç»™å…¶æ ‡è®°å®ƒæ˜¯ç‰¹æ®Šçš„ã€‚

    //æ§åˆ¶é˜´å½±å˜åŒ–çš„å‡½æ•°ï¼Œæ¯å¸§è°ƒç”¨ä¸€æ¬¡
    private void ShadowShock()
    {
        //é¦–å…ˆæ„é€ ä¸€ä¸ªæœ¬å¸§å˜åŒ–x
        BuildAFitX buildAFitX = (float deleta)
        =>
        {
            float newX = m_shadow.transform.localScale.x + deleta;
            if(newX > MinShadowSize && newX < MaxShadowSize)
            {return newX;}
            else return m_shadow.transform.localScale.x;
        };
        float x = buildAFitX(Random.Range(-indexRecoder.shellShadowRangeOfChange, 
                                          indexRecoder.shellShadowRangeOfChange));
        //ä½¿å¾—æœ¬åœ°å¤§å°æ”¹å˜ä¸º
        m_shadow.transform.localScale = new Vector3(
                                                    //x
                                                    // m_shadow.localScale.x +
                                                    // Random.Range(-indexRecoder.shellShadowRangeOfChange,
                                                    //             indexRecoder.shellShadowRangeOfChange),
                                                    x
                                                    ,
                                                    //yï¼Œzä¸å˜
                                                    m_shadow.localScale.y,
                                                    m_shadow.localScale.z);
    }

    private void Drop()
    {
        isDroping = true;
    }

    public void DestroySelf()
    {
        //åŠ¨ç”»ä¸­è°ƒç”¨ï¼Œçˆ†ç‚¸åŠ¨ç”»ç»“æŸååˆ é™¤è‡ªèº«å’Œé˜´å½±
        Destroy(gameObject);
    }

    void OnTriggerEnter2D(Collider2D other)
    {
        //Debug.Log(other.name);
        //å½“ç‚®å¼¹çˆ†ç‚¸ï¼Œæ ¹æ®ç›®æ ‡ç‰©ä½“çš„tagåˆ†åŒ–
        switch (other.tag)
        {
            case "Player":
                //ç©å®¶è¢«ç‚®å¼¹å‡»ä¸­
                Debug.Log("ç©å®¶è¢«ç‚®å¼¹å‡»ä¸­");
                break;
            case "åœ°é¢":
                //Destroy(m_shadow.gameObject);
                //Destroy(gameObject);
                Instantiate(boomObj, new Vector2(transform.position.x, transform.position.y),Quaternion.identity);
                animator.SetBool("IsBoom",true);
                if(m_shadow != null) Destroy(m_shadow.gameObject);
                isDroping = false;
                break;
            case "çŸ³å¤´":
                // Destroy(m_shadow.gameObject);
                // Destroy(gameObject);//æ‘§æ¯ç‚®å¼¹
                animator.SetBool("IsBoom",true);
                //Destroy(m_shadow.gameObject);
                isDroping = false;
                //å¦‚æœè‡ªå·±æ˜¯ç‰¹æ®Šçš„ç‚®å¼¹ï¼Œåˆ™è§¦å‘çŸ³å¤´çš„ç¨‹åºæ®µ
                if(amISpecal) other.GetComponent<Stone>().BeHitBySpecalShell();
                break;
            case "è€å…µ":
                animator.SetBool("IsBoom",true);
                isDroping = false;
                other.transform.Find("è€å…µ").GetComponent<Animator>().SetBool("IsBoomDead",true);//æ‰§è¡Œè€å…µè¢«ç‚¸æ­»åŠ¨ç”»
                break;
            // case "ç”µæŠ¥æœº":
            //     animator.SetBool("IsBoom",true);
            //     isDroping = false;//æ’­æ”¾çˆ†ç‚¸åŠ¨ç”»
            //     FindObjectOfType<M_Player>().GetComponent<Animator>().
            //     SetBool("IsBoomDead",true);//æ’­æ”¾ç©å®¶è¢«ç‚¸æ­»åŠ¨ç”»
            //     FindObjectOfType<AfterCoding>().OnDeadAnimation();
            //     break;
            case "çˆ†ç‚¸ç‚¹":
                animator.SetBool("IsBoom",true);
                isDroping = false;//æ’­æ”¾çˆ†ç‚¸åŠ¨ç”»
                FindObjectOfType<AfterCoding>().OnDeadAnimation();
                break;
        }
        if(amISpecal)
        {
            if(target!=null)target.SetBool("IsBoomDead",true);
        }
    }
    

}